# python 3
FROM ubuntu:focal

MAINTAINER K. Shankari (shankari@eecs.berkeley.edu)

# setup the correct version of node using nvm
RUN apt-get update
RUN apt-get -y install curl
RUN apt-get -y install xz-utils

# Git for checking out code
RUN apt-get -y install git

ADD start_devapp_serve.sh /start_devapp_serve.sh
# ADD autoreload.js /autoreload.js
# ADD chokidar-index.js /chokidar-index.js

#declare environment variables
ENV PHONE_REPO='https://github.com/e-mission/e-mission-phone.git'
ENV PHONE_BRANCH='master'
EXPOSE 3000

CMD ["/bin/bash", "/start_devapp_serve.sh"]
