# python 3
FROM ubuntu:latest

MAINTAINER K. Shankari (shankari@eecs.berkeley.edu)

RUN apt-get update
RUN apt-get install -y curl
RUN apt-get install -y git

# install nano and vim for editing
RUN apt-get -y install nano vim

# cleanup
RUN apt-get -y remove --purge build-essential
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

#declare environment variables
ENV DB_HOST=''
ENV WEB_SERVER_HOST=''

ADD start_script.sh /start_script.sh
ADD clone_and_start_server.sh /clone_and_start_server.sh
RUN chmod u+x /clone_and_start_server.sh

ADD index.html /index.html

EXPOSE 8080

CMD ["/bin/bash", "/clone_and_start_server.sh"]
