# python 3
FROM continuumio/miniconda3:4.5

MAINTAINER K. Shankari (shankari@eecs.berkeley.edu)

# set working directory
WORKDIR /src

# install nodejs, npm and bower
RUN apt-get update
RUN apt-get install -y build-essential
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
RUN apt-get -y install nodejs
RUN npm install -g bower

# cleanup
RUN apt-get -y remove --purge build-essential
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

#declare environment variables
ENV DB_HOST=''
ENV WEB_SERVER_HOST=''

ADD clone_and_start_server.sh /clone_and_start_server.sh
RUN chmod u+x /clone_and_start_server.sh

EXPOSE 8080

CMD ["/bin/bash", "/clone_and_start_server.sh"]
