# python 3
FROM agutt/e-mission-server:ceo_ebike_project_2022-09-19--45-23

COPY conf /conf

COPY start_script.sh /usr/src/app/.docker/start_script.sh
CMD ["/bin/bash", "/usr/src/app/.docker/start_script.sh"]
